---
# Area Labels
- name: area/docs
  color: "72CCF3"  # Light Blue
  description: >-
    Changes to documentation and guides

- name: area/examples
  color: "BC9BE3"  # Lavender
  description: >-
    Changes to example code and demonstrations

- name: area/github
  color: "F4D1B7"  # Peach
  description: >-
    Changes made to GitHub Actions

- name: area/pre-commit
  color: "84B6EB"  # Steel Blue
  description: >-
    Changes made to pre-commit hooks

- name: area/python
  color: "7BD7E0"  # Turquoise
  description: >-
    Changes to Python package configuration and dependencies

- name: area/security
  color: "FF6600"  # Orange
  description: >-
    Changes to security policies and configurations

- name: area/taskfiles
  color: "66CCFF"  # Sky Blue
  description: >-
    Changes made to Taskfiles

- name: area/tests
  color: "99CC00"  # Lime Green
  description: >-
    Changes to test files and testing infrastructure

- name: area/workspace
  color: "FF99CC"  # Pink
  description: >-
    Changes to VSCode workspace configuration

- name: area/assets
  color: "FFA07A"  # Light Salmon
  description: >-
    Changes to asset files

- name: area/templates
  color: "DA70D6"  # Orchid
  description: >-
    Changes to templates

- name: area/scripts
  color: "40E0D0"  # Turquoise
  description: >-
    Changes to script files

- name: area/src
  color: "4682B4"  # Steel Blue
  description: >-
    Changes to source code

- name: area/ci
  color: "FF4500"  # Orange Red
  description: >-
    Changes related to CI/CD configurations

- name: area/shell
  color: "556B2F"  # Dark Olive Green
  description: >-
    Changes to shell scripts

- name: area/dev
  color: "CC6699"  # Dusty Rose
  description: >-
    Changes to development tools and assets

# Renovate Labels
- name: renovate/container
  color: "9933CC"  # Purple
  description: >-
    Docker container updates via Renovate

- name: renovate/github-action
  color: "FF3366"  # Hot Pink
  description: >-
    GitHub Action updates via Renovate

- name: renovate/github-release
  color: "3399FF"  # Bright Blue
  description: >-
    GitHub Release updates via Renovate

# Semantic Type Labels
- name: type/digest
  color: "FF66CC"  # Bright Pink
  description: >-
    Dependency digest updates

- name: type/patch
  color: "FFC300"  # Golden Yellow
  description: >-
    Patch changes (fixes, updates)

- name: type/minor
  color: "FFD700"  # Gold
  description: >-
    Minor changes (features, improvements)

- name: type/major
  color: "F6412D"  # Red Orange
  description: >-
    Major changes

- name: type/break
  color: "FF0000"  # Bright Red
  description: >-
    Breaking changes

# Documentation Labels
- name: type/docs
  color: "0075CA"  # Documentation Blue
  description: >-
    Documentation updates and improvements

- name: type/core
  color: "A2EEEF"  # Light Blue
  description: >-
    Changes to core repository files and configurations
