import re

file_path = "/home/khid/Desktop/www-project-top-10-for-large-language-model-applications/2_0_vulns/translations/km-KH/LLM06_ExcessiveAgency.md"

with open(file_path, "r", encoding="utf-8") as f:
    text = f.read()

# Common terms replacements all instances
replacements = {
    "អ្នកប្រើប្រាស់ (user)": "អ្នកប្រើប្រាស់",
    "អ្នកប្រើប្រាស់ (users)": "អ្នកប្រើប្រាស់",
    "បរិបទនៃអ្នកប្រើប្រាស់ម្នាក់ៗ (individual user)": "បរិបទនៃអ្នកប្រើប្រាស់ម្នាក់ៗ",
    "អ្នកប្រើប្រាស់ម្នាក់ៗ (individual user)": "អ្នកប្រើប្រាស់ម្នាក់ៗ",
    "កម្មវិធី (application)": "កម្មវិធី",
    "ប្រព័ន្ធខាងក្រោម (downstream systems)": "ប្រព័ន្ធខាងក្រោម",
    "ប្រព័ន្ធខាងក្រោម (downstream system)": "ប្រព័ន្ធខាងក្រោម",
    "ការអនុញ្ញាត (permissions)": "ការអនុញ្ញាត",
    "សិទ្ធិ (permissions)": "សិទ្ធិ",
    "ឯកសារ (files)": "ឯកសារ",
    "ឯកសារ (file)": "ឯកសារ",
    "ឯកសារ (documents)": "ឯកសារ",
    "ផ្នែកបន្ថែម (extensions)": "ផ្នែកបន្ថែម",
    "ផ្នែកបន្ថែម (extension)": "ផ្នែកបន្ថែម",
    "ភ្នាក់ងារ (agent)": "ភ្នាក់ងារ",
    "ភ្នាក់ងារ (agents)": "ភ្នាក់ងារ",
    "ពាក្យបញ្ជា (commands)": "ពាក្យបញ្ជា",
    "ពាក្យបញ្ជា shell (shell function)": "ពាក្យបញ្ជា shell",
    "លទ្ធផល (output)": "លទ្ធផល",
    "មុខងារ (functionality)": "មុខងារ",
    "មុខងារ (functions)": "មុខងារ",
    "ប្រអប់សំបុត្រ (mailbox)": "ប្រអប់សំបុត្រ",
    "ប្រអប់សំបុត្រ (inbox)": "ប្រអប់សំបុត្រ",
    "អ៊ីមែល (emails)": "អ៊ីមែល",
    "សកម្មភាព (action)": "សកម្មភាព",
    "សកម្មភាព (actions)": "សកម្មភាព",
    "គំរូ (model)": "គំរូ",
    "ឃ្លាំង (repository)": "ឃ្លាំង",
    "សកម្មភាពដែលមិនចង់បាន (undesirable actions)": "សកម្មភាពដែលមិនចង់បាន",
    "សកម្មភាពមិនសមរម្យ (undesirable actions)": "សកម្មភាពមិនសមរម្យ",
    "សរសេរឯកសារជាក់លាក់ (specific file-writing extension)": "សរសេរឯកសារជាក់លាក់",
    "សិទ្ធិមូលដ្ឋានទិន្នន័យ (database permissions)": "សិទ្ធិមូលដ្ឋានទិន្នន័យ",
    "តារាង 'ផលិតផល' (products table)": "តារាង 'ផលិតផល'",
    "មូលដ្ឋានទិន្នន័យផលិតផល (product database)": "មូលដ្ឋានទិន្នន័យផលិតផល",
    "វិសាលភាពអប្បបរមា (minimum scope)": "វិសាលភាពអប្បបរមា",
    "សកម្មភាពដែលមានផលប៉ះពាល់ខ្ពស់ (high-impact actions)": "សកម្មភាពដែលមានផលប៉ះពាល់ខ្ពស់",
    "វិសាលភាពសុវត្ថិភាព (security scope)": "វិសាលភាពសុវត្ថិភាព",
    "សិទ្ធិអប្បបរមា (minimum privileges)": "សិទ្ធិអប្បបរមា",
    "ឃ្លាំងកូដរបស់អ្នកប្រើប្រាស់ (user's code repo)": "ឃ្លាំងកូដរបស់អ្នកប្រើប្រាស់",
    "មាតិកាប្រព័ន្ធផ្សព្វផ្សាយសង្គម (social media content)": "មាតិកាប្រព័ន្ធផ្សព្វផ្សាយសង្គម",
    "គោលការណ៍សុវត្ថិភាព (security policies)": "គោលការណ៍សុវត្ថិភាព",
    "ការអនុញ្ញាត (authorization)": "ការអនុញ្ញាត",
    "ការអនុញ្ញាតរបស់អ្នកប្រើប្រាស់ (user authorization)": "ការអនុញ្ញាតរបស់អ្នកប្រើប្រាស់",
    "ប្រតិបត្តិការ 'បង្ហោះ' (post operation)": "ប្រតិបត្តិការ 'បង្ហោះ'",
    "ទម្លាប់នៃការអនុម័តដោយអ្នកប្រើប្រាស់ (user approval routine)": "ទម្លាប់នៃការអនុម័តដោយអ្នកប្រើប្រាស់",
    "ការសម្អាតទិន្នន័យបញ្ចូល (input sanitisation)": "ការសម្អាតទិន្នន័យបញ្ចូល",
    "ត្រួតពិនិត្យ (monitor)": "ត្រួតពិនិត្យ",
    "ត្រួតពិនិត្យ (monitoring)": "ត្រួតពិនិត្យ",
    "ការកត់ត្រា (Log)": "ការកត់ត្រា",
    "កត់ត្រា (Log)": "កត់ត្រា",
    "ការកំណត់អត្រា (rate-limiting)": "ការកំណត់អត្រា",
    "ការកំណត់អត្រា (rate limiting)": "ការកំណត់អត្រា",
    "កម្មវិធីជំនួយការផ្ទាល់ខ្លួន (personal assistant app)": "កម្មវិធីជំនួយការផ្ទាល់ខ្លួន",
    "អ៊ីមែលដែលចូល (incoming emails)": "អ៊ីមែលដែលចូល",
    "អ៊ីមែលដែលចូល (incoming email)": "អ៊ីមែលដែលចូល",
    "ម៉ាស៊ីនបម្រើទិន្នន័យ (database server)": "ម៉ាស៊ីនបម្រើទិន្នន័យ",
    "អត្តសញ្ញាណ (identity)": "អត្តសញ្ញាណ",
    "សិទ្ធិ SELECT (SELECT permissions)": "សិទ្ធិ SELECT",
    "អត្តសញ្ញាណដែលមានសិទ្ធិខ្ពស់ទូទៅ (generic high-privileged identity)": "អត្តសញ្ញាណដែលមានសិទ្ធិខ្ពស់ទូទៅ",
    "កន្លែងផ្ទុកឯកសាររបស់អ្នកប្រើប្រាស់ (user's document store)": "កន្លែងផ្ទុកឯកសាររបស់អ្នកប្រើប្រាស់",
    "កន្លែងផ្ទុកឯកសារ (document repository)": "កន្លែងផ្ទុកឯកសារ",
    "គណនីមានសិទ្ធិខ្ពស់ (privileged account)": "គណនីមានសិទ្ធិខ្ពស់",
    "ឯកសាររបស់អ្នកប្រើប្រាស់ (user's documents)": "ឯកសាររបស់អ្នកប្រើប្រាស់",
    "មាតិកា (content)": "មាតិកា",
    "អ្នកវាយប្រហារ (attacker)": "អ្នកវាយប្រហារ",
    "អាសយដ្ឋានអ៊ីមែលរបស់អ្នកវាយប្រហារ (attacker's email address)": "អាសយដ្ឋានអ៊ីមែលរបស់អ្នកវាយប្រហារ",
    "ព័ត៌មានដែលរសើប (sensitive information)": "ព័ត៌មានដែលរសើប",
    "មុខងារលើសលប់ (excessive functionality)": "មុខងារលើសលប់",
    "ការអនុញ្ញាតលើសលប់ (excessive permissions)": "ការអនុញ្ញាតលើសលប់",
    "ការអនុញ្ញាតហួសហេតុ (Excessive Permissions)": "ការអនុញ្ញាតហួសហេតុ",
    "កម្មវិធីដែលមានមូលដ្ឋានលើ LLM (LLM-based app)": "កម្មវិធីដែលមានមូលដ្ឋានលើ LLM",
    "ស្វ័យភាពហួសហេតុ (Excessive Autonomy)": "ស្វ័យភាពហួសហេតុ",
    "សិទ្ធិអាន (read access)": "សិទ្ធិអាន",
    "ឯករាជ្យភាពលើសលប់ (excessive autonomy)": "ឯករាជ្យភាពលើសលប់",
    "សំបុត្រ (mail)": "សំបុត្រ",
    "បញ្ជូន (send)": "បញ្ជូន",
    "បញ្ជូន (forward)": "បញ្ជូន",
    "ផ្ទៀងផ្ទាត់ (authenticate)": "ផ្ទៀងផ្ទាត់",
    "សម័យ OAuth (OAuth session)": "សម័យ OAuth",
    "វិសាលភាពគ្រាន់តែអាន (read-only scope)": "វិសាលភាពគ្រាន់តែអាន",
    "សេវាកម្មអ៊ីមែលរបស់អ្នកប្រើប្រាស់ (user's email service)": "សេវាកម្មអ៊ីមែលរបស់អ្នកប្រើប្រាស់",
    "ម៉ាស៊ីនបម្រើទិន្នន័យ (database server)": "ម៉ាស៊ីនបម្រើទិន្នន័យ",
    "តារាង (tables)": "តារាង",
    "បញ្ចូល (insert)": "បញ្ចូល",
    "កែប្រែ (update)": "កែប្រែ",
    "លុបកំណត់ត្រា (delete records)": "លុបកំណត់ត្រា",
    "មូលដ្ឋានទិន្នន័យ (database)": "មូលដ្ឋានទិន្នន័យ",
    "ប្រព័ន្ធដែលមានមូលដ្ឋានលើ LLM (LLM-based system)": "ប្រព័ន្ធដែលមានមូលដ្ឋានលើ LLM",
    "ទាញយកមាតិកា (fetch contents)": "ទាញយកមាតិកា",
    "ប្រអប់សំបុត្ររបស់អ្នកប្រើប្រាស់ (user's mailbox)": "ប្រអប់សំបុត្ររបស់អ្នកប្រើប្រាស់",
}

for k, v in replacements.items():
    text = text.replace(k, v)

# Restore the first occurrence of key technical terms if we wiped them out by broad matching, or just manually format them:
text = text.replace("មុខងារ (functions) ឬប្រាស្រ័យទាក់ទងជាមួយប្រព័ន្ធផ្សេងទៀតតាមរយៈផ្នែកបន្ថែម", "មុខងារ (functions) ឬប្រាស្រ័យទាក់ទងជាមួយប្រព័ន្ធផ្សេងទៀតតាមរយៈផ្នែកបន្ថែម (extensions)")
text = text.replace("ប្រព័ន្ធខាងក្រោម ដែលមិនចាំបាច់សម្រាប់ប្រតិបត្តិការ", "ប្រព័ន្ធខាងក្រោម (downstream systems) ដែលមិនចាំបាច់សម្រាប់ប្រតិបត្តិការ")

with open(file_path, "w", encoding="utf-8") as f:
    f.write(text)

