---
name: "🚨 Bug Report"
description: File a bug report
title: "🚨 [BUG] - <title>"
labels: ["bug", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: |
        Steps to reproduce the behavior:
        1.
        2.
        3.

        Expected behavior:
        ...

        Actual behavior:
        ...
    validations:
      required: true

  - type: textarea
    id: possible-fix
    attributes:
      label: Any suggestions for fixing this bug?
      description: If you have an idea to fix this bug, we'd love to hear it!
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output.
      render: shell

  - type: textarea
    id: environment
    attributes:
      label: Details about your environment
      description: Please provide the following information about your environment.
      placeholder: |
        ## Your Environment
        - Go Version:
        - Operating System:
        - Browser (if applicable):
        - Relevant env vars

        Tell us what you see!
    validations:
      required: false
