---
name: "💡 Feature Request"
description: Create a new ticket for a new feature request
title: "💡 [REQUEST] - <title>"
labels: ["question"]
body:
  - type: textarea
    id: implementation_pr
    attributes:
      label: "Implementation PR"
      description: Associated pull request
      placeholder: "# Pull Request ID"
    validations:
      required: false
  - type: textarea
    id: reference_issues
    attributes:
      label: "Reference Issues"
      description: Related issues
      placeholder: "# Issue ID(s)"
    validations:
      required: false
  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: Provide a brief explanation of the feature
      placeholder: Describe your feature request
    validations:
      required: true
  - type: textarea
    id: basic_example
    attributes:
      label: "Basic Example"
      description: Provide some basic examples of your feature
      placeholder: A few specific details about your feature request
    validations:
      required: true
  - type: textarea
    id: drawbacks
    attributes:
      label: "Drawbacks"
      description: What are the drawbacks/impacts of your feature request?
      placeholder: Identify the drawbacks and impacts while remaining neutral on your feature request
    validations:
      required: true
  - type: textarea
    id: unresolved_question
    attributes:
      label: "Unresolved questions"
      description: What questions remain unresolved?
      placeholder: Identify any unresolved issues
    validations:
      required: false
