version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Containerfile
    image: rag_app
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
