---
name: Update PR Description with Rigging
on:
  pull_request:
    types: [opened]

jobs:
  update-description:
    name: Update PR Description with Rigging
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0 # full history for proper diffing

      - name: Set up Python
        uses: actions/setup-python@8d9ed9ac5c53483de85588cdf95a591a75ab9f55 # v5.5.0
        with:
          python-version: "3.13"

      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Generate PR Description
        id: description
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          DESCRIPTION="$(uv run --no-project .hooks/generate_pr_description.py --base-ref "origin/${{ github.base_ref }}" --exclude "./*.lock")"
          {
            echo "description<<EOF"
            echo "${DESCRIPTION}"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Update PR Description
        uses: nefrob/pr-description@4dcc9f3ad5ec06b2a197c5f8f93db5e69d2fdca7 # v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          content: |

            ---

            ## Generated Summary:

            ${{ steps.description.outputs.description }}

            This summary was generated with ❤️ by [rigging](https://rigging.dreadnode.io/)
